export declare const buttonRow: string
export declare const buttonText: string
export declare const card: string
export declare const cardHeader: string
export declare const cardText: string
export declare const cardTitle: string
export declare const contentGrid: string
export declare const dangerCard: string
export declare const dangerHeader: string
export declare const descriptionValue: string
export declare const divider: string
export declare const dividerContainer: string
export declare const editBlock: string
export declare const eyebrow: string
export declare const hero: string
export declare const heroCopy: string
export declare const heroMeta: string
export declare const icon: string
export declare const input: string
export declare const mainContainer: string
export declare const mainCtn: string
export declare const metaCard: string
export declare const metaCode: string
export declare const metaLabel: string
export declare const metaValue: string
export declare const noteCard: string
export declare const noteLabel: string
export declare const noteText: string
export declare const quickLink: string
export declare const quickLinkText: string
export declare const quickLinkTitle: string
export declare const readOnlyBlock: string
export declare const readOnlyHint: string
export declare const readOnlyValue: string
export declare const repoInfo: string
export declare const settingBody: string
export declare const settingHelp: string
export declare const settingIntro: string
export declare const settingRow: string
export declare const settingTitle: string
export declare const subtitle: string
export declare const textArea: string
export declare const textContainer: string
export declare const title: string
export declare const upgradeButton: string
export declare const warningBanner: string
