export declare const domainIcon: string
export declare const domainItem: string
export declare const icon: string
export declare const label: string
export declare const main: string
export declare const popoverContent: string
export declare const popoverPortal: string
export declare const popoverTarget: string
export declare const projectLabel: string
export declare const projectPill: string
export declare const repoLinks: string
export declare const sectionDivider: string
export declare const sectionLabel: string
export declare const selected: string
export declare const spaceLabel: string
export declare const spaceName: string
export declare const spaceSelector: string
