export declare const active: string
export declare const card: string
export declare const cardEntrance: string
export declare const cardHeader: string
export declare const cardIcon: string
export declare const cardMetric: string
export declare const cardStatus: string
export declare const cardTitle: string
export declare const critical: string
export declare const healthy: string
export declare const passing: string
export declare const statusDot: string
export declare const warning: string
