export declare const active: string
export declare const card: string
export declare const cardAccent: string
export declare const cardAction: string
export declare const cardBody: string
export declare const cardEntrance: string
export declare const cardEyebrow: string
export declare const cardFooter: string
export declare const cardGlow: string
export declare const cardIcon: string
export declare const cardMetric: string
export declare const cardStatus: string
export declare const cardSummary: string
export declare const cardTitle: string
export declare const cardTopline: string
export declare const critical: string
export declare const healthy: string
export declare const passing: string
export declare const statusDot: string
export declare const warning: string
