export declare const emptyState: string
export declare const grid: string
export declare const header: string
export declare const loopHealth: string
export declare const loopHealthGrid: string
export declare const loopHealthItem: string
export declare const loopHealthLabel: string
export declare const loopHealthValue: string
export declare const main: string
export declare const mcpBanner: string
export declare const mcpButton: string
export declare const mcpDot: string
export declare const mcpLabel: string
export declare const mcpStatus: string
export declare const metricItem: string
export declare const metricLabel: string
export declare const metricValue: string
export declare const metricsGrid: string
export declare const metricsPanel: string
export declare const panel: string
export declare const panelHeader: string
export declare const panelSubtitle: string
export declare const panelTitle: string
export declare const pendingLabel: string
export declare const prLink: string
export declare const remediationBadge: string
export declare const remediationItem: string
export declare const remediationList: string
export declare const remediationMeta: string
export declare const remediationPrimary: string
export declare const remediationTitle: string
export declare const subtitle: string
export declare const title: string
