export declare const eyebrow: string
export declare const grid: string
export declare const hero: string
export declare const heroActions: string
export declare const heroCopy: string
export declare const heroNote: string
export declare const heroPanel: string
export declare const main: string
export declare const primaryAction: string
export declare const secondaryAction: string
export declare const sectionEyebrow: string
export declare const sectionHeader: string
export declare const sectionSummary: string
export declare const sectionTitle: string
export declare const statCard: string
export declare const statGrid: string
export declare const statLabel: string
export declare const statusBadge: string
export declare const statusDot: string
export declare const statValue: string
export declare const subtitle: string
export declare const title: string
