export declare const bp3Active: string
export declare const bp3Button: string
export declare const bp3Card: string
export declare const bp3Control: string
export declare const bp3ControlIndicator: string
export declare const bp3Dialog: string
export declare const bp3DialogCloseButton: string
export declare const bp3DialogHeader: string
export declare const bp3Divider: string
export declare const bp3Heading: string
export declare const bp3HtmlSelect: string
export declare const bp3HtmlTable: string
export declare const bp3Icon: string
export declare const bp3Input: string
export declare const bp3IntentDanger: string
export declare const bp3IntentPrimary: string
export declare const bp3IntentSuccess: string
export declare const bp3IntentWarning: string
export declare const bp3Menu: string
export declare const bp3MenuItem: string
export declare const bp3Minimal: string
export declare const bp3OverlayBackdrop: string
export declare const bp3Popover: string
export declare const bp3Popover2: string
export declare const bp3Popover2Content: string
export declare const bp3PopoverArrowFill: string
export declare const bp3PopoverContent: string
export declare const bp3Select: string
export declare const bp3Spinner: string
export declare const bp3SpinnerHead: string
export declare const bp3Tab: string
export declare const bp3TabIndicator: string
export declare const bp3TabIndicatorWrapper: string
export declare const bp3Tag: string
export declare const bp3Toast: string
export declare const grain: string
export declare const reactRoot: string
export declare const subtlePulse: string
