export declare const activeTab: string
export declare const catalogColumns: string
export declare const catalogEyebrow: string
export declare const catalogHeader: string
export declare const catalogSummary: string
export declare const checklist: string
export declare const code: string
export declare const codeBlock: string
export declare const codeHeader: string
export declare const configGrid: string
export declare const configHint: string
export declare const copyButton: string
export declare const emptyState: string
export declare const eyebrow: string
export declare const hero: string
export declare const heroChips: string
export declare const heroCopy: string
export declare const main: string
export declare const metricLabel: string
export declare const metricList: string
export declare const metricValue: string
export declare const section: string
export declare const sectionCard: string
export declare const sectionTitle: string
export declare const setupGrid: string
export declare const statusCard: string
export declare const statusDot: string
export declare const statusHint: string
export declare const statusMeta: string
export declare const statusRow: string
export declare const statusText: string
export declare const subtitle: string
export declare const tab: string
export declare const tabs: string
export declare const title: string
export declare const toolBadge: string
export declare const toolDesc: string
export declare const toolDomain: string
export declare const toolDomainTitle: string
export declare const toolItem: string
export declare const toolItemHeader: string
export declare const toolMeta: string
export declare const toolName: string
export declare const toolNotes: string
export declare const toolRequires: string
export declare const transportDesc: string
