export declare const brandColumn: string
export declare const brandContent: string
export declare const card: string
export declare const cardChildren: string
export declare const cardColumn: string
export declare const disclaimer: string
export declare const domainGrid: string
export declare const domainTag: string
export declare const floatOrb: string
export declare const gridPan: string
export declare const heroSub: string
export declare const heroTitle: string
export declare const layout: string
export declare const logoRow: string
export declare const logoText: string
