export declare const badgeFrame: string
export declare const badgeGlyph: string
export declare const badgeSpark: string
export declare const copy: string
export declare const layout: string
export declare const logoBadge: string
export declare const logoGlow: string
export declare const logoIcon: string
export declare const main: string
export declare const meta: string
export declare const text: string
