// Copyright 2023 Harness, Inc.
// Modified by EolaFam1828 (2026) — Added SoloDev module providers.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

// WIRE INTEGRATION GUIDE FOR NEW MODULES
//
// This file documents the WireSet entries that need to be added to wire.go
// to integrate the 6 new modules: Feature Flags, Technical Debt, Security Scanner,
// Health Check Monitor, Error Tracker, and Quality Gates.
//
// NOTE: wire.go is auto-generated by the wire tool. Do NOT edit it directly.
// Instead, add the entries below to the initSystem function's wire.Build() call.
//
// HOW TO INTEGRATE:
// 1. Open cmd/gitness/wire.go
// 2. Add the following imports (if not already present) to the import block:
//
//    featureflagevents "github.com/harness/gitness/app/events/featureflag"
//    techdebtevents "github.com/harness/gitness/app/events/techdebt"
//    securityscanevents "github.com/harness/gitness/app/events/securityscan"
//    healthcheckevents "github.com/harness/gitness/app/events/healthcheck"
//    errortrackerevents "github.com/harness/gitness/app/events/errortracker"
//    qualitygatevents "github.com/harness/gitness/app/events/qualitygate"
//
// 3. Add the following WireSet entries to the wire.Build() call in initSystem() function.
//    These should be added in the appropriate alphabetical or logical position:
//
//    // Feature Flags Module
//    featureflagevents.WireSet,
//
//    // Technical Debt Module
//    techdebtevents.WireSet,
//
//    // Security Scanner Module
//    securityscanevents.WireSet,
//
//    // Health Check Monitor Module
//    healthcheckevents.WireSet,
//
//    // Error Tracker Module
//    errortrackerevents.WireSet,
//
//    // Quality Gates Module
//    qualitygatevents.WireSet,
//
// WHY THESE ENTRIES?
// - Events WireSets are required to initialize event handlers and reporters for each module
// - Controller WireSets are automatically pulled in via router.WireSet dependencies
// - Handler functions are not part of wire and are directly imported by the router
// - Store WireSets are managed separately in app/store/database/wire.go
//
// VERIFICATION STEPS:
// After updating wire.go:
// 1. Run: go generate ./cmd/gitness
// 2. Verify no wire-related build errors occur
// 3. The wire tool will automatically resolve all dependencies and generate wire_gen.go
//
// DEPENDENCIES:
// Each module has the following layers:
// - Controller: Business logic (auto-wired via controller packages)
// - Handler: HTTP request/response handling (imported directly in router)
// - Events: Domain events and event handlers (explicit WireSet needed)
// - Store: Data persistence (managed in app/store/database/wire.go)
//
// STORE INTEGRATION:
// The following Store provider functions should be in app/store/database/wire.go:
// - ProvideFeatureFlagStore
// - ProvideTechDebtStore
// - ProvideSecurityScanStore
// - ProvideHealthCheckStore
// - ProvideErrorTrackerStore
// - ProvideQualityRuleStore
// - ProvideQualityEvaluationStore
//
// These are already handled in app/store/database/wire_modules.go
